### ISSUE TITLE
Suggestion: Publish a blueprint to all projects 

### ISSUE THREAD

**Issue by samhegde** [nutanix/calm-dsl#107]
`calm publish bp <bp_name> -v <version> --publish_to_marketplace --project <project1> --project <project2> ` can publish to selected projects.  If there are significant number projects to which a particular blueprint has to be published the above syntax can be too overwhelming. Can we have a flag to enable publish to all projects?

**Comment by abhijeetkaurav1st** [comment]
Added `--all_projects/-ap` to publish bp, approve bp and , publish marketplace bp commands that will use all projects defined in context(server) to perform above operation
