### ISSUE TITLE
No output from "calm set config --project" even if project doesn't exist

### ISSUE THREAD

**Issue by digitalformula** [nutanix/calm-dsl#111]
When setting the Calm DSL project as follows, there is no output to indicate success or failure.

    calm set config --project <project>

See screenshot:

![Untitled](https://user-images.githubusercontent.com/423229/90708959-78787a00-e2de-11ea-8ad1-3e587852f789.png)

In the above example, **lab_project_cr** exists, **lab_project_xx** does not exist.

Suggest confirmation or failure is shown so the user knows if the command worked, or not.

**Comment by abhijeetkaurav1st** [comment]
Added validation of configuration before applying the changes.
