### ISSUE TITLE
Decompile does not include image_name for AhvVmResources

### ISSUE THREAD

**Issue by pipoe2h** [nutanix/calm-dsl#129]
Blueprint: 2 Services, 1x AHV and 1x Existing Machine
AHV Service: Disk 1 is empty 60GB disk; Disk 2 is CD-ROM ISO Image with bootable True

When decompiling, the AhvVmDisk.CdRom.Ide.cloneFromImageService has not reference to the image to clone leading to an error when trying to create the blueprint.

![image](https://user-images.githubusercontent.com/17649319/96573760-7f177380-12c6-11eb-86a9-227e674471ec.png)
![image](https://user-images.githubusercontent.com/17649319/96573660-627b3b80-12c6-11eb-916e-ed5d5926fc40.png)
![image](https://user-images.githubusercontent.com/17649319/96573681-69a24980-12c6-11eb-8d64-69dc19879d90.png)

**Comment by pipoe2h** [comment]
RCA: This happens if the cache is not up to date. 

Decompile process should include `update cache` with a flag to disable it if the user have done an update cache recently

**Comment by abhijeetkaurav1st** [comment]
This issue will be addressed under the changes for https://github.com/nutanix/calm-dsl/issues/115

**Comment by abhijeetkaurav1st** [comment]
Updating cache may take a lot of time. That's why it is disabled by default. 
User can use sync option to update cache before decompile.
Ex:  `calm --sync decompile bp <bp_name>`
