### ISSUE TITLE
Allow blueprint name for `calm init bp`

### ISSUE THREAD

**Issue by pipoe2h** [nutanix/calm-dsl#13]
`calm init bp` doesn not allow to pass a name. I'd like to use something like `calm init bp --name myblueprint` so I can use this command for the creation of all my new blueprints to keep consistency with the structure.

**Comment by abhijeetkaurav1st** [comment]
Now, u can use 
`calm init bp -n/--name <blueprint_name>` to create blueprint with provided name. By default it will use 'Hello' as blueprint name
