### ISSUE TITLE
Cache update in case if config_file cli option is passed

### ISSUE THREAD

**Issue by abhijeetkaurav1st** [nutanix/calm-dsl#144]
take care of version validation and update changes if config file is supplied during cli switches. (As version cache will be from existing context. ) Either update or remove version completely from cache

_Originally posted by @abhijeetkaurav1st in https://github.com/nutanix/calm-dsl/issues/115#issuecomment-687270400_

**Comment by dwivediprab** [comment]
PR: https://github.com/ideadevice/calm-dsl/pull/404
