### ISSUE TITLE
On using ntnx/calm-dsl image in a GitHub Actions workflow. It spins up the container fine with an entrypoint on “tail”. On executing any command, it is failing while looking for calm modules

### ISSUE THREAD

**Issue by abhijeetkaurav1st** [nutanix/calm-dsl#162]
question: trying to use the ntnx/calm-dsl image in a GitHub Actions workflow. It spins up the container fine with an entrypoint on “tail”; the container is running, but when it tries to execute any command inside the running container, it gets weird error messages:
```
[centos@cap-ghr-0-210324-143447 actions-runner]$ docker ps
CONTAINER ID   IMAGE           COMMAND               CREATED          STATUS         PORTS     NAMES
db2afc6421bb   ntnx/calm-dsl   "tail -f /dev/null"   11 seconds ago   Up 2 seconds             1238e6e5f0c34cb787258fad200ce854_ntnxcalmdsl_39b1b3
[centos@cap-ghr-0-210324-143447 actions-runner]$ docker container exec 1238e6e5f0c34cb787258fad200ce854_ntnxcalmdsl_39b1b3 calm --version
Traceback (most recent call last):
  File "/root/.local/bin/calm", line 5, in <module>
    from calm.dsl.cli import main
ModuleNotFoundError: No module named 'calm'
```

For more info visit: 
https://nutanix.slack.com/archives/C8FHE2Q69/p1616606887149200
https://nutanix.slack.com/archives/GHGEAFZ3K/p1616685285035700

**Comment by tuxtof** [comment]
problem is not the tail or entrypoint
just HOME env is not good and we are not look calm python module in the right place

**Comment by tuxtof** [comment]
PR #164 fix this problem

python module was installed at the global level inside so no more problem if HOME env change
