### ISSUE TITLE
Password with % is not supported

### ISSUE THREAD

**Issue by pipoe2h** [nutanix/calm-dsl#169]
If the user password for configuring DSL includes `%`, any command fails because DSL is not escaping the character. 

`configparser.InterpolationSyntaxError: '%' must be followed by '%' or '('`

It can be escaped in the ini file with duplicating the character `%%`. The other solution that I have tested and works is moving from ConfigParser to RawConfigParser in the following files:

- calm/dsl/config/init_config.py (line 31)
`config = configparser.RawConfigParser()`
- calm/dsl/config/config.py (line 16)
`config = configparser.RawConfigParser()`

My preference is the second method and not have to escape it in the ini file. 

Note: % is accepted as character by PC user creation as well as Calm SaaS API key and other third parties

**Comment by abhijeetkaurav1st** [comment]
Fixed as per https://github.com/nutanix/calm-dsl/pull/228
