### ISSUE TITLE
Support for passing existing environments in project spec file for update command

### ISSUE THREAD

**Issue by abhijeetkaurav1st** [nutanix/calm-dsl#187]
`calm update project -f <project_file>.` command update the project with the file data. All data is overrided as of now.
Need a way to pass existing environments in project file.
Ex:
```
class Project1(Project):
     envs = [Env1, Env2]
     env_refs = [Ref.Environment("Existing environment with this project")]
```
Where env_refs will take existing environments to be remain in the project

**Comment by abhijeetkaurav1st** [comment]
Or much better, if during update we will not remove existing envs from project also.

**Comment by glover-chris** [comment]
Agree with your above better comment.  We use separate environment files and do not create envs within the project file.  Maybe a switch at project update which will not remove existing?
