### ISSUE TITLE
PRIORITY - Allow custom roles to be used in acp creation.

### ISSUE THREAD

**Issue by glover-chris** [nutanix/calm-dsl#191]
Currently DSL can not add roles in acp other than stock Calm roles ,e.g., Project Admin, Operators, etc.  I am at a large customer now that has numerous custom roles that will need to be added to the projects created through DSL.  Can this request get completed as high priority?

**Comment by abhijeetkaurav1st** [comment]
Jira ticket for tracking: https://jira.nutanix.com/browse/CALM-30585
