### ISSUE TITLE
Allow bp launch environment patching with secrets

### ISSUE THREAD

**Issue by sikander27** [nutanix/calm-dsl#208]
A flag named as  `--with secret`  in the bp launch command to specify whether user want to patch credentials from environment or from bluerprint

**Comment by abhijeetkaurav1st** [comment]
Fixed as per https://github.com/nutanix/calm-dsl/pull/209.
We can use `calm launch bp <bp_name> -e <env_name> -ws -i` to  launch bluepriunt after patching with environment env_name  and keeping credential secret preserved
