### ISSUE TITLE
[Bug] Parameter typo in calm publish runbook --existing_markeplace_runbook

### ISSUE THREAD

**Issue by nutken** [nutanix/calm-dsl#232]
**Describe the bug**
For the command `calm publish runbook` the option `--existing_markeplace_runbook` is missing the 't' in marketplace. It should be `--existing_marketplace_runbook`

**Branch/Container**
Master
https://github.com/nutanix/calm-dsl/blob/884be6b2cf4298f97dc8b064efbd6c02d8018086/calm/dsl/cli/marketplace_runbook_commands.py#L292

**Comment by dwivediprab** [comment]
Issue if fixed in DSL v3.7.2.2. Hence closing it.
