### ISSUE TITLE
[Improvement] add functionality --all_projects to command calm update marketplace

### ISSUE THREAD

**Issue by pipoe2h** [nutanix/calm-dsl#256]
The option --all_projects already exists for specific marketplace tasks, but not for when updating. If you create projects after publishing a blueprint, there is no way of updating the blueprint with the new projects at once. If you pass a project, it will overwrite the existing projects and leave only the one provided during the command.

**Current behaviour**
#107 

**Expected behaviour**
Be able to pass --all_projects to update marketplace for picking all the projects

**Comment by dwivediprab** [comment]
Issue fixed in DSL v3.7.2.2. Hence closing it.
