### ISSUE TITLE
Calm create project does not enable quotas

### ISSUE THREAD

**Issue by glover-chris** [nutanix/calm-dsl#266]
**Describe the bug**
Creating a project with quotas does enable quotas within the project.

**Branch/Container**
Master 03/28/2023

**To Reproduce**
Create a project using the templae.

https://github.com/nutanix/calm-dsl/blob/master/examples/Project/demo_project.py

Quotas are not enabled.

**Comment by abhijeetkaurav1st** [comment]
Fixed in release 3.7.0
