### ISSUE TITLE
Decompiled script from dynamic variable has no identifying name

### ISSUE THREAD

**Issue by kingsleyck** [nutanix/calm-dsl#27]
Steps to reproduce: 

1. Create a dynamic variable with type EScript.
2. Decompile the blueprint.
3. Script is decompiled with the name: **_Task_Task.py**

**Comment by abhijeetkaurav1st** [comment]
Issue is fixed via commit id: _3f2b39a84f5892b1c33edc0cb8a00ef0f54a20d3_.
