### ISSUE TITLE
[Bug] cluster macro is not supported in command calm decompile bp

### ISSUE THREAD

**Issue by glover-chris** [nutanix/calm-dsl#283]
**Describe the bug**
When decompiling a bp with cluster macro, we receive the following error:

[2024-01-18 12:58:04] [ERROR] [calm.dsl.builtins.models.calm_ref:669] Entity with type ahv_cluster and uuid @@{target_cluster.uuid}@@ not found in cache. Please update cache

**Branch/Container**
master

**To Reproduce**
1. Decompile a bp with cluster macro.

**Expected behavior**
Bp decompiles.

**Findings/Troubleshooting Done**
See error above.

**Available Logs/Data**
If there is any CLI command stack traceback or some logs

**Screenshots**

** System Configuration:**
- OS: [e.g. Linux]
- Python: [e.g. Python 3.6.8]

**Additional context**

**Comment by dwivediprab** [comment]
PR: https://github.com/ideadevice/calm-dsl/pull/395
