### ISSUE TITLE
[Bug] fail to decompile UEFI boot_type in command calm decompile bp

### ISSUE THREAD

**Issue by ntnx-dlane** [nutanix/calm-dsl#289]
**Describe the bug**
When decompiling a blueprint that has UEFI and Secure boot enabled, calm-dsl 3.7.2.1, does not show that boot_type field as UEFI.

**Branch/Container**
master

**To Reproduce**
create a BP with UEFI and secure boot.  Use Calm DSL to decompile said blueprint.  Review blueprint.py file and observe no settings for UEFI.

**Expected behavior**
boot_type needs to be observed as part of the decompile.

**Findings/Troubleshooting Done**
Confirmed with multiple blueprints, and multiple users.

**Available Logs/Data**
n/a

**Screenshots**
n/a

** System Configuration:**
- OS: mac 14.2.x
- Python: 3.11.2

**Additional context**
n/a

**Comment by dwivediprab** [comment]
PR: https://github.com/ideadevice/calm-dsl/pull/390
(Added decompilation for boot_type)
