### ISSUE TITLE
Decompile fails to escape backslashes in regex strings resulting in incorrect recompile

### ISSUE THREAD

**Issue by nutken** [nutanix/calm-dsl#291]
**Describe the bug**
A Simple.multiline type profile variable with a regex validation string including tokens such as \r, \n, \t do not get properly escaped during decompile.  Recompiling the generated blueprint results in an incorrect validation string. A subsequent decompile of the recompiled blueprint will result in failure.

**Branch/Container**
Tag v3.7.2.1

**To Reproduce**
Create a BP with a multiline profile variable. Configure a regex validation string which contains tokens such as \r, \n, \t.
Decompile blueprint and observe the generated regex value for that variable in the blueprint.py. You will see the tokens are not escaped (ie, \\r, \\n, \\t, etc). Compile generated blueprint and observe the incorrect regex in the GUI. Likewise, decompile this blueprint and observe the decompile fails.

**Expected behavior**
The blueprint should be decompiled such that the resulting output can be compiled to produce a functionally equivalent blueprint.

**Findings/Troubleshooting Done**
If the generated regex string were a raw string, the issue should not occur.

**Screenshots**
Original multi-line field DSL (created with escaped tokens)
![image](https://github.com/nutanix/calm-dsl/assets/53309211/a5b23567-2d7a-497c-a740-b8fc4d13d828)
Original multi-line field in GUI (token present in regex)
![image](https://github.com/nutanix/calm-dsl/assets/53309211/5aa259e1-cb29-4c58-810d-c363b6c90be0)

Decompiled multi-line field DSL(tokens not escaped)
![image](https://github.com/nutanix/calm-dsl/assets/53309211/f37ea2a0-e5e6-4f08-b869-7e852a17b66f)
Recompiled multi-line field in GUI (tokens not visible in regex)
![image](https://github.com/nutanix/calm-dsl/assets/53309211/ff4e20be-7305-4c37-b3c1-376e83425200)

** System Configuration:**
Python 3.11.6 / Mac OS X
PC 2023.04 / Calm 3.7.2.1

**Additional context**

**Comment by dwivediprab** [comment]
Issue is fixed in DSL v3.7.2.2 release, Hence closing it.
