### ISSUE TITLE
Get Blueprint Filter doesn't work

### ISSUE THREAD

**Issue by pipoe2h** [nutanix/calm-dsl#38]
Executing `calm get bps -f jg` doesn't work

> [2020-04-15 13:32:10] calm.dsl.api.connection [ERROR] Error Response: {'error': '{\n  "api_version": "3.1", \n  "code": 500, \n  "message_list": [\n    {\n      "details": {}, \n      "message": "list index out of range", \n      "reason": "INTERNAL_ERROR"\n    }\n  ], \n  "state": "ERROR"\n}\n', 'code': 500}

**Comment by abhijeetkaurav1st** [comment]
As discussed earlier -f flag should be used for proper flag string. For name search use `-n` flag
