### ISSUE TITLE
Fix terminal emulation issues with running actions with --watch

### ISSUE THREAD

**Issue by digitalformula** [nutanix/calm-dsl#44]
Related command:

    calm run action <action_name> --app <app_name> --watch

Dynamic terminal output displays some lines on the same lines as previous.  Also, when process has finished, odd unicode-like characters are left at the terminal cursor.

Screenshot of broken lines attached.

![calm-run-action-watch](https://user-images.githubusercontent.com/423229/79539893-8917aa00-80ca-11ea-9ade-68aad5e6f5dc.png)

Environment when reproducing issue:

- Kubuntu 20.04
- Konsole 19.12.3
- $TERM value **xterm-256color**

**Comment by baljanak** [comment]
@kdabi Can you check this issue ?

**Comment by baljanak** [comment]
@kdabi Any update on this issue ?

**Comment by baljanak** [comment]
Fixed in https://github.com/nutanix/calm-dsl/pull/51

**Comment by kdabi** [comment]
created separate issue for unicode characters issue [#52](https://github.com/nutanix/calm-dsl/issues/52)
