### ISSUE TITLE
Readiness probe is not working with latest DSL master

### ISSUE THREAD

**Issue by charanteja333** [nutanix/calm-dsl#73]
Old DSL implementation has readiness probe with default credential defined as below 
__readiness_probe["credential"] = ref(default_credential)__
Same is failing with below error on latest master
```
  File "lamp-v4.py", line 129, in MySQLSubstrate
    readiness_probe["credential"] = ref(default_credential)
TypeError: 'ReadinessProbeType' object does not support item assignment
```
I had to change it to __readiness_probe.credential = ref(default_credential)__ to make it work

**Comment by abhijeetkaurav1st** [comment]
Readiness_probe is supposed to give using `readiness_probe()` helper now. So dict methods will not work. Try `readiness_probe.credential = ref(default_credential)`

So closing this issue as this is not needed from now on.
