### ISSUE TITLE
Default value of secret variable shows blank while launching bp

### ISSUE THREAD

**Issue by Suryadhulipudi** [nutanix/calm-dsl#88]
Problem Statement:
Hi Team, We observed that when we try to launch bp with secret variables it is getting blank.

Steps to reproduce:
1. Try to launch a bp which has secret vars.

Findings/Troubleshooting Done:
Attaching a screenshot.
![image](https://user-images.githubusercontent.com/13795705/85690292-1130b600-b6f1-11ea-8fe6-ed3418a66a96.png)

**Comment by abhijeetkaurav1st** [comment]
Secrets are never returned to client. So it is expected to have empty value shown here.
So for now secrets should be passed separately while launching bp either interactively or non-interactively(through --launch_params flag).

**Comment by abhijeetkaurav1st** [comment]
It won't be fixed until we have some server support for getting the value of secrets at client side

**Comment by abhijeetkaurav1st** [comment]
Workaround till now: 
1. Launch those bp  with UI .
2. Always pass value during launch with interactively/non-interactively though dsl.
